# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ddb73559e417e3669f42421db9d94c9bc84c83fa8d037ab597e7230d2d56076b37fa61687ec93f6c1351465d6584d68992478cfcd84a68a3b3a52a3b7cf850a

test:
  secret_key_base: cd7c3b6ef0dae4ce81d87d34347a9bf4f40b5b5d2c7796e8ae3a645d0b7b3d6428ef29dd20dc29a9c717d5a5d29456e6efb097970b1ddf3dbde96033baa41903

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["RAILSCONFEVENTS_SECRET_KEY_BASE"] %>
